### ISSUE TITLE
djangocms deleted every file in the dir I ran it in

### ISSUE THREAD

**Issue by danmur** [nephila/djangocms-installer#156]
I followed the instructions on the website to install but it has errored and deleted everything from the dir I ran it in (which had about four years worth of projects in it, hope everything was checked in):

    daniel:djangotest daniel$ pwd
    /Users/daniel/tmp/djangotest
    daniel:djangotest daniel$ mkdir adir
    daniel:djangotest daniel$ touch adir/afile
    daniel:djangotest daniel$ ls -alh
    total 0
    drwxr-xr-x   3 daniel  staff   102B 12 Jan 17:41 .
    drwxr-xr-x  20 daniel  staff   680B 12 Jan 17:41 ..
    drwxr-xr-x   3 daniel  staff   102B 12 Jan 17:41 adir
    daniel:djangotest daniel$ ~/pythons/djangocms/bin/pip install -U djangocms-installer
    DEPRECATION: --download-cache has been deprecated and will be removed in the future. Pip now automatically uses and configures its cache.
    Requirement already up-to-date: djangocms-installer in /Users/daniel/pythons/djangocms/lib/python2.7/site-packages
    Requirement already up-to-date: dj-database-url in /Users/daniel/pythons/djangocms/lib/python2.7/site-packages (from djangocms-installer)
    Requirement already up-to-date: pip in /Users/daniel/pythons/djangocms/lib/python2.7/site-packages (from djangocms-installer)
    Requirement already up-to-date: six in /Users/daniel/pythons/djangocms/lib/python2.7/site-packages (from djangocms-installer)
    Requirement already up-to-date: argparse in /Users/daniel/pythons/djangocms/lib/python2.7/site-packages (from djangocms-installer)
    Requirement already up-to-date: requests in /Users/daniel/pythons/djangocms/lib/python2.7/site-packages (from djangocms-installer)
    daniel:djangotest daniel$ ~/pythons/djangocms/bin/djangocms -p . djangotest
    Database configuration (in URL format) [default sqlite://localhost/project.db]:
    django CMS version (choices: 2.4, 3.0, stable, develop) [default stable]: 3.0
    Django version (choices: 1.4, 1.5, 1.6, 1.7, stable) [default stable]:
    Activate Django I18N / L10N setting (choices: yes, no) [default yes]:
    Install and configure reversion support (choices: yes, no) [default yes]:
    Languages to enable. Option can be provided multiple times, or as a comma separated list. Only language codes supported by Django can be used here: english
    Optional default time zone [default America/Chicago]:
    Activate Django timezone support (choices: yes, no) [default yes]:
    Activate CMS permission management (choices: yes, no) [default yes]:
    Use Twitter Bootstrap Theme (choices: yes, no) [default no]:
    Use custom template set [default no]:
    Load a starting page with examples after installation. Choose "no" if you use a custom template set. (choices: yes, no) [default no]:
    Command /usr/bin/python -c "import setuptools;__file__='/private/var/folders/l0/kz49q1zd2wqd55pdjmn3vqn00000gn/T/pip_build_daniel/django-cms/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/l0/kz49q1zd2wqd55pdjmn3vqn00000gn/T/pip-u0brlT-record/install-record.txt --single-version-externally-managed failed with error code 1 in /private/var/folders/l0/kz49q1zd2wqd55pdjmn3vqn00000gn/T/pip_build_daniel/django-cms
    Storing complete log in /Users/daniel/Library/Logs/pip.log
    Traceback (most recent call last):
      File "/Users/daniel/pythons/djangocms/bin/djangocms", line 9, in <module>
        load_entry_point('djangocms-installer==0.7.0', 'console_scripts', 'djangocms')()
      File "/Users/daniel/pythons/djangocms/lib/python2.7/site-packages/djangocms_installer/main.py", line 47, in execute
        shutil.rmtree(config_data.project_directory)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 256, in rmtree
        onerror(os.rmdir, path, sys.exc_info())
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 254, in rmtree
        os.rmdir(path)
    OSError: [Errno 22] Invalid argument: '.'
    daniel:djangotest daniel$ ls -alh
    total 0
    drwxr-xr-x   2 daniel  staff    68B 12 Jan 17:43 .
    drwxr-xr-x  20 daniel  staff   680B 12 Jan 17:41 ..

I assumed from the help description that -p was the parent directory for the new project, if that's not the case it would be good to make that clear (not that deleting everything in that dir would ever be acceptable!).

**Comment by yakky** [comment]
Sorry to hear that, @danmur
`-p` has always been intended as a directory specific for the project (it's where the `manage.py` goes)
The above PR minimise the issue by asking confirmation before removing and providing more info about the `-p` parameter

**Comment by danmur** [comment]
Yep understand. I think the confusing thing for me is that essentially that snippet I pasted is right on the django-cms homepage:

    $ pip install --upgrade virtualenv
    $ virtualenv env
    $ source env/bin/activate
    (env) $ pip install djangocms-installer
    (env) $ djangocms -p . my_demo

Just opening a terminal and typing that might be enough to delete a home directory. If -p is intended to be the directory the new project goes in would it not make sense to error out straight away if it's not empty?

**Comment by yakky** [comment]
Adding the check as proposed

**Comment by yakky** [comment]
Version 0.7.1 has been released to solve this
