### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by 00091701** [nephila/djangocms-installer#160]
Failure occurred. Do you want to cleanup by removing C:\Temp\dj\ProjectSite? [Y/N] y
Removing everything under C:\Temp\dj\ProjectSite
Traceback (most recent call last):
File "C:\Temp\dj\ProjectSite\env\Scripts\djangocms-script.py", line 9, in 
File "C:\Temp\dj\ProjectSite\env\lib\site-packages\djangocms_installer\main.py", line 30, in execute
File "C:\Temp\dj\ProjectSite\env\lib\site-packages\djangocms_installer\django__init__.py", line 43, in create_pro
ject
File "c:\Python27\Lib\subprocess.py", line 535, in check_call
retcode = call(popenargs, *kwargs)
File "c:\Python27\Lib\subprocess.py", line 522, in call
return Popen(popenargs, *kwargs).wait()
File "c:\Python27\Lib\subprocess.py", line 710, in init
errread, errwrite)
File "c:\Python27\Lib\subprocess.py", line 958, in _execute_child
startupinfo)
WindowsError: [Error 193] %1 ist keine zulõssige Win32-Anwendung

Info:
https://github.com/divio/django-cms/issues/3777#issuecomment-70638142

**Comment by yakky** [comment]
Could you translate the german message?

**Comment by 00091701** [comment]
DE:
WindowsError: [Error 193] %1 ist keine zulässige Win32-Anwendung

EN:
WindowsError: [Error 193] %1 is not a valid Win32 application

**Comment by yakky** [comment]
@00091701 woult you please check by installing https://github.com/nephila/djangocms-installer/archive/feature/hotfixes.zip?

**Comment by 00091701** [comment]
@yakky ,

I am sorry but it does not work.

After "a long time" I got this error message:

Creating the project
Please wait while I install dependencies
Dependencies installed
Creating the projectTraceback (most recent call last):
  File "C:\Temp\Django\ProjectSite\env\Scripts\django-admin.py", line 2, in <module>
    from django.core import management
ImportError: No module named django.core
Failure occurred. Do you want to cleanup by removing C:\Temp\Django\ProjectSite? [Y/N]

**Comment by yakky** [comment]
Ok, this is a different error, which is quite weird as it apparently finds the django-admin.py command but not the Django code.
Could you check the environment and what happens if you run ``django-admin.py startproject projekt `` manually in the same virtualenv?

**Comment by 00091701** [comment]
Test 1
--------
C:\Temp\Django>mkdir ProjectSite

C:\Temp\Django>cd ProjectSite

C:\Temp\Django\ProjectSite>
C:\Temp\Django\ProjectSite>virtualenv --no-site-packages env
New python executable in env\Scripts\python.exe
Installing setuptools, pip...done.

C:\Temp\Django\ProjectSite>
C:\Temp\Django\ProjectSite>env\Scripts\activate.bat
(env) C:\Temp\Django\ProjectSite>pip install pillow
Downloading/unpacking pillow
Installing collected packages: pillow
Successfully installed pillow
Cleaning up...

(env) C:\Temp\Django\ProjectSite>python django-admin.py startproject projekt
python: can't open file 'django-admin.py': [Errno 2] No such file or directory

(env) C:\Temp\Django\ProjectSite>

Test 2
--------
(env) C:\Temp\Django\ProjectSite>pip install django
Downloading/unpacking django
Installing collected packages: django
Successfully installed django
Cleaning up...

(env) C:\Temp\Django\ProjectSite>python django-admin.py startproject projekt
python: can't open file 'django-admin.py': [Errno 2] No such file or directory

(env) C:\Temp\Django\ProjectSite>
