### ISSUE TITLE
django-cms not using LANGUAGE_CODE for core translations when installed from djangocms-installer

### ISSUE THREAD

**Issue by GabLeRoux** [nephila/djangocms-installer#163]
Please have a look to this:
https://github.com/divio/django-cms/issues/3798

Not quite sure if this is an issue with `djangocms-installer` itself or `django-cms`.

**Comment by yakky** [comment]
looks unrelated to django CMS installer.
Keeping this open for the moment

**Comment by GabLeRoux** [comment]
This is indeed unrelated, downgraded django version 3.0.7 and french translations are working.

**Comment by yakky** [comment]
Closing this, keeping the CMS one open
