### ISSUE TITLE
Installer 0.7.2. Page Title never changes when you choose the option Twitter Bootstrap Theme = YES

### ISSUE THREAD

**Issue by JeymyAV** [nephila/djangocms-installer#166]
Hello,

When you install djangocms with the installer using the Bootstrap Theme, the name of the Page title always is displayed "This is my new project home page", because this never change.

The problem is when the djangocms-installer create a new project in some templates this tag is missing:
{% block title %}{% page_attribute 'title' %}{% endblock title %}.

This no happen if you install without the bootstrap option, because the tag exists.

Below templates name that  they are missing the prevous tag: 
page.htlm and feature.htlm.

Please, can you fix it for the next release?

Thank you.
Jeyme

**Comment by yakky** [comment]
Thanks for reporting, #166 fix this
