### ISSUE TITLE
Possible fix for ImportError: No module named django.core

### ISSUE THREAD

**Issue by hendersonanalytics** [nephila/djangocms-installer#168]
I tried your installer in a virtualenv in Windows 7.  I kept getting the same error as this guy: https://github.com/nephila/djangocms-installer/issues/165

I ended up having to change one line in djangocms_installer\django\__init__.py

In the create_project function, I changed the syntax from:

subprocess.check_call(' '.join(['django-admin.py', 'startproject'] + args), shell=True)

to:

subprocess.check_call(' '.join(['python virtualenv_path\Scripts\django-admin.py', 'startproject'] + args), shell=True)

After that, the installation process went pretty smoothly.  Not sure how others have tackled this problem, but I was thinking that this might be helpful to others Windows users trying to install django cms.

Update: I'm using Python 2.7.8

**Comment by yakky** [comment]
Is the ``py`` extension correctly registered? (see https://github.com/nephila/djangocms-installer#windows-support)

**Comment by hendersonanalytics** [comment]
I tried that solution before applying my fix and it didn't solve the django.core error.  I got the idea for my fix from the Django project docs - check out the "Running virtualenv on Windows" section on this page:

https://docs.djangoproject.com/en/1.6/faq/troubleshooting/#troubleshooting-django-admin-py

Thanks.
