### ISSUE TITLE
wrong djangocms-flash version in dependencies (BUG)

### ISSUE THREAD

**Issue by arinker** [nephila/djangocms-installer#175]
release djangocms-flash==0.2.0 doesn't exist

must be djangocms-flash==0.1.0 instead

https://github.com/divio/djangocms-flash/releases

**Comment by yakky** [comment]
Fixed by releasing djangocms-flash 0.2.0 (which was ready but not uploaded by mistake)

**Comment by arinker** [comment]
Thank you!
