### ISSUE TITLE
djangoCMS Installer not working with Pillow 2.8.0 on Ubuntu 14.04

### ISSUE THREAD

**Issue by rosco77** [nephila/djangocms-installer#185]
When trying to run djangoCMS installer on an Ubuntu 14.04 box it fails with Pillow 2.8.0.  The following output is shown

```
EnvironmentError: Pillow is not compiled with PNG support, see 'Libraries installation issues' documentation section: http://djangocms-installer.readthedocs.org/en/latest/libraries.html.
Pillow is not compiled with JPEG support, see 'Libraries installation issues' documentation section: http://djangocms-installer.readthedocs.org/en/latest/libraries.html
```
Followed guidelines in the above readthedocs pages but still failed.  Installer then worked when using Pillow==2.7.0

**Comment by yakky** [comment]
Does pillow correctly compiles with jpeg/png when installing outside the installer? You can easily tell that as pillow prints a table of supported formats after installation

**Comment by rosco77** [comment]
I've actually logged this for someone else who was having a problem with the installer on the django-cms irc channel.  We tried installing Pillow outside the djangoCMS-installer with a normal django installation using a test import of a JPEG (taken from here https://gist.github.com/636693/f1bf002e349766ce993ce779c757ddaf76cfdfb4).  

This passed as expected and we tried the recommendations a couple of times listed in the docs and on that TestCase.  Nothing fixed it until I got him to install Pillow 2.7.0.

**Comment by yakky** [comment]
Ok, I'll try to use the above test. Possibly pillow 2.8 changed something in the Image.thumbnail handling

**Comment by rosco77** [comment]
Cheers Yakky.  Thanks for DjangoCon BTW.  Felt very inspired.  I'm hoping to get the new docs to you soon.

**Comment by yakky** [comment]
Thanks. Currently working on new material regarding testing django / django CMS applications
