### ISSUE TITLE
Menu markup in Bootstrap theme renders landing pages inaccessible

### ISSUE THREAD

**Issue by evildmp** [nephila/djangocms-installer#186]
https://github.com/nephila/djangocms-installer/blob/2251f6e7689ce40ee7b99f84b524d3d3d335b1fa/djangocms_installer/share/templates/bootstrap/menu.html#L8

This is not an ideal configuration for the menu - in particular, it makes it impossible to use applications whose Apphooks include nice homepages, such as Events or News & Blog.

I think the behaviour of for example http://www.django-cms.org/en/blog/ would be better.

**Comment by yakky** [comment]
Fixed by #352
