### ISSUE TITLE
[Question] Installing packages into global site-packages?

### ISSUE THREAD

**Issue by philippeowagner** [nephila/djangocms-installer#192]
```...
creating /Library/Python/2.7/site-packages/cms
error: could not create '/Library/Python/2.7/site-packages/cms': Permission denied
```
Is it intended that packages are installed to the global ``site-packages``? 

(Running OS X)

**Comment by yakky** [comment]
@philippeowagner definitely not. But djangocms-installer relies on virtualenv / pip behaving properly. Any context regarding that error?

**Comment by philippeowagner** [comment]
@yakky so virtualenv did't worked for me. Will try to reproduce and update the issue in case I have sth. useful for djangocms-installer. Thanks!

**Comment by yakky** [comment]
You're welcome. Closing this. Feel free to reopen in case

**Comment by philippeowagner** [comment]
Can't reproduce!
