### ISSUE TITLE
Pillow is not compiled with PNG and JPEG support

### ISSUE THREAD

**Issue by sunilsrikumar** [nephila/djangocms-installer#193]
Almost tired of this error :)
1.

/venv/local/lib/python2.7/site-packages/djangocms_installer/install/init.py", line 56, in check_install
EnvironmentError: Pillow is not compiled with PNG support, see 'Libraries installation issues' documentation section: http://djangocms-installer.readthedocs.org/en/latest/libraries.html.
Pillow is not compiled with JPEG support, see 'Libraries installation issues' documentation section: http://djangocms-installer.readthedocs.org/en/latest/libraries.html
2.

/venv/local/lib/python2.7/site-packages/pip/vendor/requests/packages/urllib3/util/ssl.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
InsecurePlatformWarning

Can anyone help me please?
I'm using Linux Mint 17.2

Sunil

**Comment by yakky** [comment]
@sunilsrikumar is this #174 of any help? which version of djangocms-installer are you trying? the second error is due to some  python/pip conflicts regarding SSL management and it's not related to djangocms-installer

**Comment by sunilsrikumar** [comment]
@yakky its djangocms-installer 0.7.9.

Agree, second error is due to python/pip conflict. Trying to resolve as referred in Django documentation but no luck. Would appreciate if you can help :) Thank you @yakky

**Comment by yakky** [comment]
what if you install pillow manually? Which libraries is compiled with?

**Comment by ZeroXn** [comment]
i had this 'jpeg' error too, but instead of trying to figure it out, i installed mezzanine, which uses the same pillow version and worked without a problem

**Comment by sunilsrikumar** [comment]
@yakky Unfortunately earlier it was not working. But Just now I tired djangocms-installer and got installed in one shot. Thank you so much for resolving the issue.

**Comment by sunilsrikumar** [comment]
@ZeroXn I do agree with you. I'm a huge fan of Mezzanine and used it for 25+ projects till yet. Undoubtedly, mezzanine is smooth & awesome for beginners to expert. At the same time, I pledge my support to django-cms too.

**Comment by yakky** [comment]
@sunilsrikumar @ZeroXn until 0.7.8 there was an incompatibility with some pillow versions / platforms. Newer version should be much more stable in this respect

**Comment by fivethreeo** [comment]
On alpine linux i had to copy /lib/ to /usr/lib/ to get pillow to pick up zlib.

**Comment by yakky** [comment]
@sunilsrikumar @fivethreeo @ZeroXn Could you test the "verbose" branch providing --verbose option on the command line? (use pip install https://github.com/nephila/djangocms-installer/archive/verbose.zip to update)

**Comment by sunilsrikumar** [comment]
@yakky @ZeroXn @fivethreeo I think django-cms installer is much more stable now, all the packages including pillow are getting installed smoothly. djangocms3.2 release is awesome, I can see lot of code cleanup activity.

**Comment by yakky** [comment]
@sunilsrikumar thanks for the heads up, and your kind words!
