### ISSUE TITLE
Call to django-admin assumes django-admin.py in same dir as sys.executable

### ISSUE THREAD

**Issue by josh-atkins-dev** [nephila/djangocms-installer#194]
# Problem
The installer (main.py) calls `django.create_project(config_data)` line 32, which fails with error:
```
subprocess.CalledProcessError: Command '/usr/bin/python /usr/bin/django-admin.py startproject <project name> .' returned non-zero exit status 2
```
if `django-admin.py` is not in the same directory as the python executable.
In my case here, the system executable is in `/usr/bin/python` but the django-admin.py is in `/usr/local/bin/django-admin.py`

# Set up
My `PATH` is `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`

May be of interest, I am using a Docker [(What is Docker?)](https://www.docker.com/whatisdocker) container with a clean Debain/Jessie, `apt-get install build-essential git python python-dev python-setuptools software-properties-common sqlite3 libtiff5-dev libjpeg62-turbo-dev zlib1g-dev libfreetype6-dev`
then `easy_install pip `
then `pip install djangocms_installer`
and finally `djangocms -p . <project name>`

# Workaround

Make a symlink: `ln -s /usr/local/bin/django-admin.py /usr/bin/django-admin.py`

# Notes
This could very well be an error on my part in set up/configuration, but I can't think of any point at which I could have easily altered config settings/paths. As I am using a super clean environment and the tools I'm using are aimed at out-of-the-box functionality, perhaps the djangocms_installer source shouldn't make the assumption above?

If interested, here is my Dockerfile:
```
FROM debian:jessie
# ORIGINAL MAINTAINER Matt Bentley <mbentley@mbentley.net>
# https://github.com/mbentley/docker-django-uwsgi-nginx
MAINTAINER Josh Atkins <josh.atkins.dev@gmail.com>

RUN (apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential git python python-dev python-setuptools software-properties-common sqlite3 &&\
			apt-get install -y libtiff5-dev libjpeg62-turbo-dev zlib1g-dev libfreetype6-dev)

RUN (easy_install pip)
RUN pip install djangocms_installer && ln -s /usr/local/bin/django-admin.py /usr/bin/django-admin.py

# alongside the Dockerfile, need "./project_dir/requirements.txt"
ADD project_dir/requirements.txt /opt/django/project_dir/requirements.txt
RUN pip install -r /opt/django/project_dir/requirements.txt
ADD . /opt/django/

VOLUME ["/opt/django/project_dir"]
EXPOSE 8000
```

**Comment by yakky** [comment]
@josh-atkins-dev djangocms-installer is meant to be used with virtualenv, and the absolute path is basically required to make this work in windows environment
The requiremdn for django-admin path is documented https://github.com/nephila/djangocms-installer#warning and it's not going to change soon, unless we can come up with a solution 100% working on Windows

**Comment by josh-atkins-dev** [comment]
@yakky ah right I missed that, my mistake - thanks for the info re docs!
