### ISSUE TITLE
allow passing custom `pip install` options like `--no-index --find-links=~/wheels/`

### ISSUE THREAD

**Issue by muayyad-alsadi** [nephila/djangocms-installer#201]
I usually pass `--find-links=~/wheels/` to `pip install` to cache all downloaded packages. please add `--pip-options` so I can type something like this 

```
djangocms-installer --pip-options="--no-index --find-links=~/wheels/" -p my_demo -f my_demo 
```

**Comment by yakky** [comment]
Nice idea

**Comment by muayyad-alsadi** [comment]
https://github.com/nephila/djangocms-installer/pull/202
