### ISSUE TITLE
fail to install depency on window 7 

### ISSUE THREAD

**Issue by formula123** [nephila/djangocms-installer#203]
I made my demo project according to document , But I found an error, I could not solve it. I have installed Python  3.5, also I have installed python 2.7.10 but didn't add to environment path.
#Here is report:
C:\Users\lxy>pip list
Django (1.8.4)
nester-zzl (1.0.0)
pip (7.1.2)
setuptools (18.2)
urllib3 (1.12)
virtualenv (13.1.2)

C:\Users\lxy>virtualenv env
Using base prefix 'c:\\users\\lxy\\appdata\\local\\programs\\python\\python35-32
'
New python executable in env\Scripts\python.exe
Installing setuptools, pip, wheel...done.

C:\Users\lxy>env\Scripts\activate
(env) C:\Users\lxy>pip install djangocms-installer
Requirement already satisfied (use --upgrade to upgrade): djangocms-installer in
 c:\users\lxy\env\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): six in c:\users\lxy\en
v\lib\site-packages (from djangocms-installer)
Requirement already satisfied (use --upgrade to upgrade): tzlocal in c:\users\lx
y\env\lib\site-packages (from djangocms-installer)
Requirement already satisfied (use --upgrade to upgrade): pip in c:\users\lxy\en
v\lib\site-packages (from djangocms-installer)
Requirement already satisfied (use --upgrade to upgrade): dj-database-url in c:\
users\lxy\env\lib\site-packages (from djangocms-installer)
Requirement already satisfied (use --upgrade to upgrade): argparse in c:\users\l
xy\env\lib\site-packages (from djangocms-installer)
Requirement already satisfied (use --upgrade to upgrade): pytz in c:\users\lxy\e
nv\lib\site-packages (from tzlocal->djangocms-installer)

(env) C:\Users\lxy>assoc .py = Python.file
.py = Python.file

(env) C:\Users\lxy>ftype Python.file = "C:\Users\lxy\env\Scripts\python.exe" "%1
" %*
Python.file = "C:\Users\lxy\env\Scripts\python.exe" "%1" %*

(env) C:\Users\lxy>cd iceyBlog

(env) C:\Users\lxy\iceyBlog>djangocms -p . mysite
Database configuration (in URL format) [default sqlite://localhost/project.db]:

django CMS version (choices: 2.4, 3.0, 3.1, stable, develop) [default stable]:
Django version (choices: 1.4, 1.5, 1.6, 1.7, 1.8, stable) [default stable]:
Activate Django I18N / L10N setting (choices: yes, no) [default yes]:
Install and configure reversion support (choices: yes, no) [default yes]:
Languages to enable. Option can be provided multiple times, or as a comma separa
ted list. Only language codes supported by Django can be used here: en
Optional default time zone [default Asia/Shanghai]:
Activate Django timezone support (choices: yes, no) [default yes]:
Activate CMS permission management (choices: yes, no) [default yes]:
Use Twitter Bootstrap Theme (choices: yes, no) [default no]: yes
Use custom template set [default no]:
Load a starting page with examples after installation (english language only). C
hoose "no" if you use a custom template set. (choices: yes, no) [default no]: ye
s
Creating the project
Please wait while I install dependencies
Command "c:\users\lxy\env\scripts\python.exe -c "import setuptools, tokenize;__f
ile__='C:\\Users\\lxy\\AppData\\Local\\Temp\\pip-build-427wc17u\\Pillow\\setup.p
y';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n',
 '\n'), __file__, 'exec'))" install --record C:\Users\lxy\AppData\Local\Temp\pip
-uf_grw2i-record\install-record.txt --single-version-externally-managed --compil
e --install-headers c:\users\lxy\env\include\site\python3.5\Pillow" failed with
error code 1 in C:\Users\lxy\AppData\Local\Temp\pip-build-427wc17u\Pillow
Failure occurred. Do you want to cleanup by removing C:\Users\lxy\iceyBlog? [Y/N
] 
(I could not find file folder pip-build-427wc17u)

**Comment by yakky** [comment]
@formula123 What happens if you install pillow beforehand (``pip install pillow``)
Also: Python 3.5 is not currently tested, so it's not guaranteed to work
Eventually check the FAQs http://djangocms-installer.readthedocs.org/en/latest/faq.html
