### ISSUE TITLE
Boostrapping fails with AttributeError: module 'html.parser' has no attribute 'HTMLParseError'

### ISSUE THREAD

**Issue by ghachey** [nephila/djangocms-installer#213]
On my MAC OS X bootstrapping fails with the following.

AttributeError: module 'html.parser' has no attribute 'HTMLParseError'
Failure occurred. Do you want to cleanup by removing /Users/ghachey/Development/Python/tutorial-project? [Y/N] Y

I have Python 3.5 installed using brew. I use Python's venv for virtual environment. This was done in a virgin virtual environment. I selected most default from the script (stablet djangocms and stablet Django). It seeems the script choose to install Django 1.7 which had a known bug using HTMLParseError which is deprecated from Python 3.3 onwards and removed in Python 3.5, as per the [official documentation](https://docs.python.org/3/library/html.parser.html#html.parser.HTMLParseError)

I'm new to djangocms so I may have done something wrong though I am not new to Python and Django.

Manually choosing Django version 1.8 seem to avoid this error (Django 1.8 fixed the above bug).

**Comment by yakky** [comment]
@ghachey only Django 1.8 is compatible with Python 3.5 (and only unofficially compatible AFAIK).
Currently installer ignores python version dependencies WRT Django and django CMS versions selection, so you have to know in advance the right Django version to install.
Making it python version aware is achievable, but can't provide an estimated schedule right now

**Comment by ghachey** [comment]
Thanks. Yes, its a little deceiving that one selects a version only to be ignored :) But it's fine I had everything working soon after. Was just reporting to document this issue.
