### ISSUE TITLE
Uses equivalent of Bootstrap 2 when Bootstrap 4 is soon to be released

### ISSUE THREAD

**Issue by mfcovington** [nephila/djangocms-installer#216]
Bootstrap 3 allows its styling to look like Bootstrap 2 by using `bootstrap-theme.min.css`. When choosing the `Use Twitter Bootstrap Theme` option, `djangocms-installer` includes both the Bootstrap 3 stylesheet and this [Bootstrap 2 'reversion' stylesheet](https://github.com/nephila/djangocms-installer/blob/0306e9f5c11ab43acc099f8dcd7022bc2ad56f4a/djangocms_installer/share/templates/bootstrap/base.html#L9).

Given that [Bootstrap 4](http://v4-alpha.getbootstrap.com) is soon to be released, what are the thoughts regarding removing `bootstrap-theme.min.css` from the `Use Twitter Bootstrap Theme` option? Or at least letting the user choose whether to install "v2" or v3?

**Comment by yakky** [comment]
@mfcovington removing ``bootstrap-theme.min.css`` as suggested.
Templates are still not meant as a base for "real" project templates, but just way to quickly setup an instance that does not looks ugly.
Not using bootstrap in my job it's hard for me to keep up with its releases.
