### ISSUE TITLE
Some packages are not installed (Debian, Raspberry Pi)

### ISSUE THREAD

**Issue by evildmp** [nephila/djangocms-installer#221]
I'm trying this out on a Raspberry Pi running Raspbian (in effect, Debian) Jessie in a Python 3.4 virtualenv.

After having apparently installed dependencies, and during the ``Creating the project`` phase, I'll get tracebacks.

First it was an import error for polymorphic. ``pip freeze`` confirmed it wasn't installed. ``pip install django-filer`` *did* install it, and I was able to continue.

Then, an import error for appconf, also not installed. And so on.

It appears that something in the chain of requirements is breaking, without it being picked up at all. Not sure whether this is an issue in Raspbian, 3.4 or the installer.

**Comment by yakky** [comment]
Well, if you get tracebacks, it's entirely possible that packages are not installed, it's normal pip behavior.
But I agree that understanding what's going on during the project setup it's very tricky at times: I'm going to put some kind of "debug mode" in the installer to understand what's going on

**Comment by evildmp** [comment]
@yakky Definitely, the (random) packages somehow did not get installed. But the tracebacks are not from pip, they are from a later command that assumed they were installed, and tried to import them.

So it seems to me that the pip commands exited without error, even though they didn't actually complete their work.

**Comment by evildmp** [comment]
As you can see, the installer believes (I guess because pip has told it so) that all dependencies have been successfully installed:

```Creating the project
Please wait while I install dependencies
Dependencies installed
Creating the projectTraceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/pi/testenv/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/pi/testenv/lib/python3.4/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/pi/testenv/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/pi/testenv/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/pi/testenv/lib/python3.4/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/pi/testenv/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/pi/testenv/lib/python3.4/site-packages/cmsplugin_filer_image/models.py", line 11, in <module>
    from .conf import settings
  File "/home/pi/testenv/lib/python3.4/site-packages/cmsplugin_filer_image/conf.py", line 4, in <module>
    from appconf import AppConf
ImportError: No module named 'appconf'
Failure occurred. Do you want to cleanup by removing /home/pi/testproject? [Y/N] 
```

**Comment by yakky** [comment]
@evildmp thanks for your report. I need to get my hands on a Raspberry Pi!

**Comment by evildmp** [comment]
@yakky maybe Debian Jessie and a Python 3.4 virtualenv would be good enough to reproduce.

**Comment by yakky** [comment]
Nope :) I regularely use that combination in development and production servers, without issues

**Comment by evildmp** [comment]
This is what's installed, after running the installer, and also pip installing django-filer by hand.

Running Python 3.4.2, pip 1.5.6. Requests doesn't seem to be installed at all.
```
Django==1.8.7
Django-Select2==4.3.2
Pillow==3.0.0
Unidecode==0.04.18
argparse==1.4.0
cmsplugin-filer==1.0.0
dj-database-url==0.3.0
django-classy-tags==0.6.2
django-cms==3.2.0
django-filer==1.0.4
django-formtools==1.0
django-mptt==0.7.4
django-polymorphic==0.7.2
django-reversion==1.8.7
django-sekizai==0.8.2
django-treebeard==3.0
djangocms-admin-style==1.0.6
djangocms-column==1.5
djangocms-flash==0.2.0
djangocms-googlemap==0.3
djangocms-inherit==0.1
djangocms-installer==0.8.3
djangocms-link==1.7.1
djangocms-style==1.5
djangocms-text-ckeditor==2.8.0
easy-thumbnails==2.2.1
html5lib==0.9999999
pytz==2015.7
six==1.10.0
tzlocal==1.2
```

**Comment by yakky** [comment]
@evildmp could you try to update to pip 7.1.2 before running the installer?

**Comment by evildmp** [comment]
It works!

Updating pip to 7.1.2 does the trick. Thanks.

**Comment by remram44** [comment]
Ran into this today. The installer doesn't install django-polymorphic then fails because it cannot import polymorphic. Please fix.

**Comment by yakky** [comment]
@remram44 are you on raspberry pi too? which are the cms / django version you chose? which version of the installer are you using?

**Comment by remram44** [comment]
Somehow it didn't reproduce when I started from scratch to make you a transcript today... might have been a quirk of pip (I did have to run the installer several times because dependencies failed to compile (I was missing libjpeg & the like), it's possible pip messed up. We all know how pip is...)

**Comment by yakky** [comment]
@remram44 definitely, it's kind of temperamental! Feel free to open a new issue if you encounter this again
