### ISSUE TITLE
djangocms-installer freezes on migrations

### ISSUE THREAD

**Issue by sobolevn** [nephila/djangocms-installer#230]
I have a problem installing Django-CMS. 

    (myenv)MacBook-Nikita:django_cms_test sobolev$ djangocms -p . landing
    Database configuration (in URL format) [default sqlite://localhost/project.db]: 
    django CMS version (choices: 2.4, 3.0, 3.1, 3.2, stable, develop) [default stable]: 
    Django version (choices: 1.4, 1.5, 1.6, 1.7, 1.8, stable) [default stable]: 
    Activate Django I18N / L10N setting (choices: yes, no) [default yes]: 
    Install and configure reversion support (choices: yes, no) [default yes]: 
    Languages to enable. Option can be provided multiple times, or as a comma separated list. Only language codes supported by Django can be used here: 
    Languages to enable. Option can be provided multiple times, or as a comma separated list. Only language codes supported by Django can be used here: 
    Languages to enable. Option can be provided multiple times, or as a comma separated list. Only language codes supported by Django can be used here: en_EN
    Optional default time zone [default Europe/Moscow]: 
    Activate Django timezone support (choices: yes, no) [default yes]: 
    Activate CMS permission management (choices: yes, no) [default yes]: 
    Use Twitter Bootstrap Theme (choices: yes, no) [default no]: 
    Use custom template set [default no]: 
    Load a starting page with examples after installation (english language only). Choose "no" if you use a custom template set. (choices: yes, no) [default no]: 

It freezes on the following step:

> Applying djangocms_link.0001_initial... OK
> Applying djangocms_link.0002_auto_20140929_1705... OK
> Applying djangocms_link.0003_auto_20150212_1310... OK
> Applying djangocms_link.0004_auto_20150708_1133... OK
> Applying djangocms_link.0005_auto_20151003_1710... OK
> Applying djangocms_picture.0001_initial... OK
> Applying djangocms_picture.0002_auto_20151018_1927... OK
> Applying djangocms_style.0001_initial... OK
> Applying djangocms_teaser.0001_initial... OK
> Applying djangocms_text_ckeditor.0001_initial... OK
> Applying djangocms_video.0001_initial... OK
> Applying menus.0001_initial... OK
> Applying reversion.0001_initial... OK
> Applying reversion.0002_auto_20141216_1509... OK
> Applying sessions.0001_initial... OK

I have waited for almost 20 minutes. No progress. I have tried creating a project in a clean `virtualenv`. The same result.   
Here's my setup: Mac OS X 10.9.5, Python 2.7.5, djangocms-installer==0.8.4

**Comment by sobolevn** [comment]
I have solved the issue by moving to `djangocms-installer==0.8.4`. Now it works.

**Comment by yakky** [comment]
@sobolevn horrible regression in 0.8.4 :(
Thanks for spotting this, preparing a hotfix release

**Comment by yakky** [comment]
@sobolevn merged the hotfix, could you test https://github.com/nephila/djangocms-installer/archive/develop.zip

**Comment by sobolevn** [comment]
Yes, it's fine now:

    Applying sessions.0001_initial... OK
    Creating admin user
    Username (leave blank to use 'sobolev'):

**Comment by yakky** [comment]
@sobolevn thanks, releasing 0.8.5 shortly
