### ISSUE TITLE
Problem with cmsplugin-filer-image in latest installer

### ISSUE THREAD

**Issue by maxkeogh** [nephila/djangocms-installer#233]
Hi,

I set up a fresh install of DjangoCMS using this link as the guide: http://docs.django-cms.org/en/develop/introduction/install.html
I chose cms version 3.1, and django version 1.8. The install went fine and runserver brought up the standard page as expected. However, when I edited the page and added an image the plugin instance on the Structure page showed Image <Empty>
I have another cms instance where the images do work. I checked the versions of the installed components and they were slightly earlier versions. The versions that work are:
cmsplugin-filer==1.0.0
django-filer==1.0.2
Pillow==3.0.0

On the latest install that produces the error the versions are:
cmsplugin-filer==1.0.1
django-filer==1.0.6
Pillow==3.1.0

I downgraded these 3 components and I could then add images onto the page.
I thought I should let you know of this error on these versions.

Kind regards
max

**Comment by yakky** [comment]
@maxkeogh looks like an error in cmsplugin-filer plugin with django CMS 3.1, you'd better open an issue on https://github.com/divio/cmsplugin-filer repository, I think

**Comment by maxkeogh** [comment]
Hi yakky,

Many thanks for this. I will do.

Best wishes
Max
