### ISSUE TITLE
LOCALE_PATHS is not settled up if I choose several languages in wizard

### ISSUE THREAD

**Issue by akolpakov** [nephila/djangocms-installer#246]
After installation with several languages, for example `en` and `se` I've got `settings.py` with several languages:
```
LANGUAGES = (
    ## Customize this
    ('en', gettext('en')),
    ('se', gettext('se')),
)
```

But without ``LOCALE_PATHS``. This variable is important for switching languages in middleware ``django.middleware.locale.LocaleMiddleware``. And after installation is impossible to use multi language website, because language is not switching by url ``http://mysite/se``. Such request redirected to ``http://mysite/en/se`` and user get an error ``404 Not Found``.

To fix it you need:
Add to settings.py:
```
LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)
```

Call for each language
```
./manage makemessages --locale se
```

Compile messages
```
./manage compilemessages --locale se
```

I can propose a PR for this bug, just say that you merge it.

**Comment by yakky** [comment]
@akolpakov sorry for missing this. ``LOCALE_PATHS`` does not play any role in URL recognition. It looks more like you did not enable i18n in the wizard options.
Adding explicit ``LOCALE_PATHS`` is a good idea anyway, so feel free to propose a PR to add it

**Comment by akolpakov** [comment]
Actually it plays role. In function [check_for_language](https://github.com/django/django/blob/master/django/utils/translation/trans_real.py#L418) django is trying to find language in locale paths. And if there is no language, it does not accept this path.
Call stack for this kind of request: 
```
 File "django/middleware/locale.py", line 32, in process_request
    request, check_path=check_path)
File "django/utils/translation/trans_real.py", line 497, in get_language_from_request
    lang_code = get_language_from_path(request.path_info)
File "django/utils/translation/trans_real.py", line 481, in get_language_from_path
    return get_supported_language_variant(lang_code, strict=strict)
File "django/utils/translation/trans_real.py", line 458, in get_supported_language_variant
    if code in supported_lang_codes and check_for_language(code):
File "django/utils/translation/trans_real.py", line 418, in check_for_language
```

**Comment by yakky** [comment]
@akolpakov could you provide a sample project that trigger this error? I can't reproduce this

**Comment by yakky** [comment]
Closing due to lack of feedback
