### ISSUE TITLE
can't dump config

### ISSUE THREAD

**Issue by diramazioni** [nephila/djangocms-installer#247]
Greetings, just after the djangocms-installer wizard has gratefully finished, I wanted to dump the config.
following from [here](http://djangocms-installer.readthedocs.org/en/latest/usage.html )  I run
`djangocms -f -p . mysite`
`djangocms --config-dump config.ini -p . mysite`
and got
`Path "." already exists and is not empty, please choose a different one
If you want to use this path anyway use the -s flag to skip this check.`
and the -s flag it's useless since it check just after ` if os.path.exists`

Also in the docs reference _djangocms_installer_ that it's now djangocms

**Comment by yakky** [comment]
@diramazioni config can't be (currently) dumped after the project has been created (at least not using the same path as the original project)
You can run ``djangocms --config-dump config.ini -p /other/path mysite`` though
Where did you find the wrong reference in the docs?

**Comment by yakky** [comment]
Closing due to lack of feedback
