### ISSUE TITLE
UnicodeDecodeError after running installer

### ISSUE THREAD

**Issue by m-aciek** [nephila/djangocms-installer#250]
Hello, I've got an error when running `djangocms -p . my_demo`:
```
Traceback (most recent call last):
  File "/…/bin/djangocms", line 11, in <module>
    sys.exit(execute())
  File "/…/lib/python2.7/site-packages/djangocms_installer/main.py", line 15, in execute
    config_data = config.parse(sys.argv[1:])
  File "/…/lib/python2.7/site-packages/djangocms_installer/config/__init__.py", line 144, in parse
    [path for path in os.listdir(args.project_directory) if not path.startswith('.')]):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 3: ordinal not in range(128)
```
Regards,
Maciej

**Comment by yakky** [comment]
@m-aciek could you provide the option you entered in the installer prompt?
Also what is the complete path of the current directory?

**Comment by m-aciek** [comment]
I was unable to recreate the problem. It worked well as I was trying to recreate it. I'm very sorry for the hassle. At that time it crashed before any prompt.

**Comment by yakky** [comment]
Sometimes transient connection error can trigger unexpected behaviors, thanks for updating the status
