### ISSUE TITLE
The installer raised an AttributeError: 'Settings' object has no attribute 'ROOT_URLCONF'

### ISSUE THREAD

**Issue by lgmcode** [nephila/djangocms-installer#263]
Hello, when I try to install django-cms with this installer in a clean virtualenv with python2.7, I got this error at the end of the installation. The complete console output is printed below. Could you please figure out why I got this error.

(venv)lgm@myserver:~/testcms/mysite$ djangocms -f -p . mysite
Database configuration (in URL format) [default sqlite://localhost/project.db]:
django CMS version (choices: 3.2, stable, rc, develop) [default stable]:
Django version (choices: 1.8, 1.9, stable) [default stable]:
Activate Django I18N / L10N setting; this is automatically activated if more than language is provided (choices: yes, no) [default yes]:
Install and configure reversion support (choices: yes, no) [default yes]:
Languages to enable. Option can be provided multiple times, or as a comma separated list. Only language codes supported by Django can be used here: en-us
Optional default time zone [default Asia/Harbin]:
Activate Django timezone support (choices: yes, no) [default yes]:
Activate CMS permission management (choices: yes, no) [default yes]:
Use Twitter Bootstrap Theme (choices: yes, no) [default no]:
Use custom template set [default no]:
Load a starting page with examples after installation (english language only). Choose "no" if you use a custom template set. (choices: yes, no) [default no]:
Creating the project
Please wait while I install dependencies
Dependencies installed
Creating the project
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/lgm/testcms/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/home/lgm/testcms/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/lgm/testcms/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/lgm/testcms/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 398, in execute
    self.check()
  File "/home/lgm/testcms/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/lgm/testcms/venv/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/lgm/testcms/venv/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 9, in check_url_config
    resolver = get_resolver()
  File "/home/lgm/testcms/venv/local/lib/python2.7/site-packages/django/utils/lru_cache.py", line 100, in wrapper
    result = user_function(*args, **kwds)
  File "/home/lgm/testcms/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 151, in get_resolver
    urlconf = settings.ROOT_URLCONF
  File "/home/lgm/testcms/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'ROOT_URLCONF'
The installation failed.
Do you want to clean up by removing /home/lgm/testcms/mysite?
        Warning: this will delete all files in:
                /home/lgm/testcms/mysite
Do you want to cleanup? [y/N] y
Removing everything under /home/lgm/testcms/mysite

**********************************************************

Check documentation at http://djangocms-installer.rtfd.org

**********************************************************

Traceback (most recent call last):
  File "/home/lgm/testcms/venv/bin/djangocms", line 9, in <module>
    load_entry_point('djangocms-installer==0.9.b1', 'console_scripts', 'djangocms')()
  File "/home/lgm/testcms/venv/local/lib/python2.7/site-packages/djangocms_installer/main.py", line 41, in execute
    django.setup_database(config_data)
  File "/home/lgm/testcms/venv/local/lib/python2.7/site-packages/djangocms_installer/django/__init__.py", line 376, in setup_database
    output = subprocess.check_output(command, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 544, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/home/lgm/testcms/venv/bin/python', u'-W', u'ignore', u'manage.py', u'migrate']' returned non-zero exit status 1
(venv)lgm@myserver:~/testcms/mysite$

**Comment by yakky** [comment]
@lgmcode thanks for this very accurate report. Could you try version djangocms-installer 0.8.10?
0.9b1 is largely untested in real projects and I don't advise to use it, yet.
If the error still occurs, could not clean the generated project and provide the generated settings file?

**Comment by lgmcode** [comment]
I tried again with djangocms-installer 0.8.10, very unfortunate it failed again. The command I used and the log output is as below, and the generated settings file (122 lines) is pasted below too (It's strange that I can't attach it below, so it's rendered by markdown interpreter and is not easy to read, sorry for your unconvenient):

(venv)lgm@myserver:~/testcms/mysite$ pip install djangocms-installer==0.8.10
(venv)lgm@myserver:~/testcms/mysite$ djangocms -f -p . mysite
Database configuration (in URL format) [default sqlite://localhost/project.db]:
django CMS version (choices: 2.4, 3.0, 3.1, 3.2, 3.3, stable, rc, develop) [default stable]:
Django version (choices: 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, stable) [default stable]:
Activate Django I18N / L10N setting; this is automatically activated if more than language is provided (choices: yes, no) [default yes]:
Install and configure reversion support (choices: yes, no) [default yes]:
Languages to enable. Option can be provided multiple times, or as a comma separated list. Only language codes supported by Django can be used here: en
Optional default time zone [default Asia/Harbin]:
Activate Django timezone support (choices: yes, no) [default yes]:
Activate CMS permission management (choices: yes, no) [default yes]:
Use Twitter Bootstrap Theme (choices: yes, no) [default no]:
Use custom template set [default no]:
Load a starting page with examples after installation (english language only). Choose "no" if you use a custom template set. (choices: yes, no) [default no]:
Creating the project
Please wait while I install dependencies
Dependencies installed
Creating the project
The installation failed.
Do you want to clean up by removing /home/lgm/testcms/mysite?
        Warning: this will delete all files in:
                /home/lgm/testcms/mysite
Do you want to cleanup? [y/N]


**********************************************************

Check documentation at http://djangocms-installer.rtfd.org

**********************************************************

Traceback (most recent call last):
  File "/home/lgm/testcms/venv/bin/djangocms", line 9, in <module>
    load_entry_point('djangocms-installer==0.8.10', 'console_scripts', 'djangocms')()
  File "/home/lgm/testcms/venv/local/lib/python2.7/site-packages/djangocms_installer/main.py", line 38, in execute
    django.patch_settings(config_data)
  File "/home/lgm/testcms/venv/local/lib/python2.7/site-packages/djangocms_installer/django/__init__.py", line 226, in patch_settings
    raise Exception()
Exception
(venv)lgm@myserver:~/testcms/mysite$

# The content of the settings.py file
"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.9c1.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'fywo2&balxhr65x@y2(!2=@&h&sju!mfz5i&my_67rt87zo%no'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATIC_URL = '/static/'

**Comment by yakky** [comment]
@lgmcode thanks. settings file looks ok. is ``DJANGO_SETTINGS_MODULE`` set in your environment, perhaps?

**Comment by yakky** [comment]
@lgmcode could you try installing this version https://github.com/nephila/djangocms-installer/archive/feature/pin_plugins.zip? 

    pip install https://github.com/nephila/djangocms-installer/archive/feature/pin_plugins.zip

**Comment by yakky** [comment]
could you also post the result of ``pip freeze``? Is the virtualenv created from scratch?

**Comment by lgmcode** [comment]
DJANGO_SETTINGS_MODULE is not set in my environment, `echo $DJANGO_SETTINGS_MODULE` outputs nothing, `pip freeze` outputs three package names:

```
(venv)lgm@myserver:~/testcms$ pip freeze
argparse==1.2.1
distribute==0.6.24
wsgiref==0.1.2
```

I tried this new version:
`pip install https://github.com/nephila/djangocms-installer/archive/feature/pin_plugins.zip`
but it still failed as before, the generated settings.py changes nothing except for a different SECRET_KEY

Oh yes, my OS is Ubuntu 12.04, don't know if this could do a little help

**Comment by yakky** [comment]
@lgmcode did you run the ``pip freeze`` before or after the installer run?

**Comment by lgmcode** [comment]
This `pip freeze` is executed before the installer run.
I would have wanted to paste the output of `pip freeze` after the installing, but my server just encountered some network problems. I'll do that tomorrow after the network returns to normal.
Thanks a lot for your patience, I really want to install this django-cms.

**Comment by yakky** [comment]
@lgmcode thanks for your tests. I'm really wondering where this error comes from. Whenever you are able to run the tests again, please post a ``pip freeze`` after installer run. BTW: You installed the installer in the clean virtualenv, right?

**Comment by lgmcode** [comment]
I think it's clean. I didn't install any packages in the global python environment, and every time before running this installer I create a new virtualenv.

**Comment by yakky** [comment]
thanks for the updates. Scratching my head about the causes of the failure.
Another approach is using dump mode (http://djangocms-installer.readthedocs.io/en/latest/usage.html#dump-mode) to enerate the requirements file, installing the packages manually using pip and then launching the installer again with the same options plus ``-n`` to generate the project. This alows to isolate package installation issues from project generation ones

**Comment by yakky** [comment]
The line in you settings file that reads ``Generated by 'django-admin startproject' using Django 1.9c1.`` is kind of surprising. That should actually display ``1.8.13`` or ``1.9.7`` according to the selected Django version.
Does your pip uses the ``--pre`` flag by default?

**Comment by yakky** [comment]
@lgmcode did you manage to reproduce this?

**Comment by lgmcode** [comment]
Sorry, I didn't continue using this installer after that, instead I installed the django-cms by hand and it works fine now, but still thanks for your help.

**Comment by yakky** [comment]
Good you still managed to install django CMS :)
