### ISSUE TITLE
Returned Non-Zero Exit Status -9

### ISSUE THREAD

**Issue by ashrafmys** [nephila/djangocms-installer#298]
Hi all, 
I keep getting this error when running this installer. Any idea why ? 

`Traceback (most recent call last):
  File "/home/ashr/env/bin/djangocms", line 11, in <module>
    sys.exit(execute())
  File "/home/ashr/env/local/lib/python2.7/site-packages/djangocms_installe                                                                                        r/main.py", line 41, in execute
    django.setup_database(config_data)
  File "/home/ashr/env/local/lib/python2.7/site-packages/djangocms_installe                                                                                        r/django/__init__.py", line 388, in setup_database
    output = subprocess.check_output(command, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/home/ashr/env/bin/python', u'-W'                                                                                        , u'ignore', u'manage.py', u'migrate']' returned non-zero exit status -9`

**Comment by yakky** [comment]
could you provide the version yand the full arguments / options you use?
Also, try to run it with ``--verbose`` , which will provide more detailed output

**Comment by ashrafmys** [comment]
Hi yakky. Thanks for the response.


Additional info:
OS : ubuntu 16.04.1 LTS
Python version : 2.7.12

I turned on the verbose like you said and follow exactly like what's on the official tutorial page

Below is the parameters and output:

` 
(env) ~/tutorial$ djangocms --verbose -f -p . mysite
Creating the project
Please wait while I install dependencies
Package install command: install django-cms<3.5 djangocms-admin-style>=1.2,<1.3 django-treebeard>=4.0,<5.0 djangocms-text-ckeditor>=3.2.1 djangocms-link>=1.8 djangocms-style>=1.7 djangocms-googlemap>=0.5 djangocms-snippet>=1.9 djangocms-video>=2.0 djangocms-column>=1.6 easy_thumbnails django-filer>=1.2 cmsplugin-filer>=1.1 Django<1.9 pytz django-classy-tags>=0.7 html5lib>=0.999999,<0.99999999 Pillow>=3.0 django-sekizai>=0.9 django-select2<5.0six
Requirement already satisfied: django-cms<3.5 in /home/ashrafmys/env/lib/python2.7/site-packages
Requirement already satisfied: djangocms-admin-style<1.3,>=1.2 in /home/ashrafmys/env/lib/python2.7/site-packages
Requirement already satisfied: django-treebeard<5.0,>=4.0 in /home/ashrafmys/env/lib/python2.7/site-packages
Requirement already satisfied: djangocms-text-ckeditor>=3.2.1 in /home/ashrafmys/env/lib/python2.7/site-packages
Requirement already satisfied: djangocms-link>=1.8 in /home/ashrafmys/env/lib/python2.7/site-packages
Requirement already satisfied: djangocms-style>=1.7 in /home/ashrafmys/env/lib/python2.7/site-packages
Requirement already satisfied: djangocms-googlemap>=0.5 in /home/ashrafmys/env/lib/python2.7/site-packages
Requirement already satisfied: djangocms-snippet>=1.9 in /home/ashrafmys/env/lib/python2.7/site-packages
Requirement already satisfied: djangocms-video>=2.0 in /home/ashrafmys/env/lib/python2.7/site-packages
Requirement already satisfied: djangocms-column>=1.6 in /home/ashrafmys/env/lib/python2.7/site-packages
Requirement already satisfied: easy_thumbnails in /home/ashrafmys/env/lib/python2.7/site-packages
Requirement already satisfied: django-filer>=1.2 in /home/ashrafmys/env/lib/python2.7/site-packages
Requirement already satisfied: cmsplugin-filer>=1.1 in /home/ashrafmys/env/lib/python2.7/site-packages
Requirement already satisfied: Django<1.9 in /home/ashrafmys/env/lib/python2.7/site-packages
Requirement already satisfied: pytz in /home/ashrafmys/env/lib/python2.7/site-packages
Requirement already satisfied: django-classy-tags>=0.7 in /home/ashrafmys/env/lib/python2.7/site-packages
Requirement already satisfied: html5lib<0.99999999,>=0.999999 in /home/ashrafmys/env/lib/python2.7/site-packages
Requirement already satisfied: Pillow>=3.0 in /home/ashrafmys/env/lib/python2.7/site-packages
Requirement already satisfied: django-sekizai>=0.9 in /home/ashrafmys/env/lib/python2.7/site-packages
Requirement already satisfied: django-select2<5.0six in /home/ashrafmys/env/lib/python2.7/site-packages
Requirement already satisfied: django-formtools>=1.0 in /home/ashrafmys/env/lib/python2.7/site-packages (from django-cms<3.5)
Requirement already satisfied: djangocms-attributes-field>=0.1.1 in /home/ashrafmys/env/lib/python2.7/site-packages (from djangocms-link>=1.8)
Requirement already satisfied: django-polymorphic<0.9,>=0.7 in /home/ashrafmys/env/lib/python2.7/site-packages (from django-filer>=1.2)
Requirement already satisfied: django-mptt<0.9,>=0.6 in /home/ashrafmys/env/lib/python2.7/site-packages (from django-filer>=1.2)
Requirement already satisfied: Unidecode<0.05,>=0.04 in /home/ashrafmys/env/lib/python2.7/site-packages (from django-filer>=1.2)
Requirement already satisfied: django-appconf in /home/ashrafmys/env/lib/python2.7/site-packages (from cmsplugin-filer>=1.1)
Requirement already satisfied: six in /home/ashrafmys/env/lib/python2.7/site-packages (from html5lib<0.99999999,>=0.999999)
Requirement already satisfied: olefile in /home/ashrafmys/env/lib/python2.7/site-packages (from Pillow>=3.0)
Requirement already satisfied: setuptools in /home/ashrafmys/env/lib/python2.7/site-packages (from django-polymorphic<0.9,>=0.7->django-filer>=1.2)Dependencies installed
Creating the project
Project creation command: /home/ashrafmys/env/bin/python /home/ashrafmys/env/bin/django-admin.py startproject mysite /home/ashrafmys/tutorial
Database setup commands: /home/ashrafmys/env/bin/python -W ignore manage.py migrate
The installation has failed.


*****************************************************************

Check documentation at https://djangocms-installer.readthedocs.io

*****************************************************************

Traceback (most recent call last):
  File "/home/ashrafmys/env/bin/djangocms", line 11, in <module>
    sys.exit(execute())
  File "/home/ashrafmys/env/local/lib/python2.7/site-packages/djangocms_installer/main.py", line 41, in execute
    django.setup_database(config_data)
  File "/home/ashrafmys/env/local/lib/python2.7/site-packages/djangocms_installer/django/__init__.py", line 388, in setup_database
    output = subprocess.check_output(command, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/home/ashrafmys/env/bin/python', u'-W', u'ignore', u'manage.py', u'migrate']' returned non-zero exit status -9
`

**Comment by yakky** [comment]
Sorry, I lost this notification. Unfortunately it looks like some unforeseen failure in migrate.
Could you launch python manage.py migrate from the tutorial directory to hae a more detailed report?

**Comment by yakky** [comment]
Did you manage to make this work, do you have any further information to provide?

**Comment by LEEVE** [comment]
Ubuntu 16.04.3 x64
Python 3.5.2

I've tried to do this many times, and I get the same results:
The project gets created but I get this error, so I am not sure what is missing from the files that are being added under my cmsproject, and why I get this error??
Here is a list of the files created
>>(cms-d) root@stack-dev1:~/cms-d/cmsproject# dir
cmssite  create_user.py  manage.py  media  project.db  static
>>(cms-d) root@stack-dev1:~/cms-d/cmsproject/cmssite# dir
__init__.py  __pycache__  settings.py  static  templates  urls.py  wsgi.py
>>(cms-d) root@stack-dev1:~/cms-d/cmsproject/cmssite/templates# ls
base.html  fullwidth.html  sidebar_left.html  sidebar_right.html


>>root@stack-dev1:~/cms-d# virtualenv cms-d
Using base prefix '/usr'
New python executable in /root/cms-d/cms-d/bin/python3
Also creating executable in /root/cms-d/cms-d/bin/python
Installing setuptools, pip, wheel...done.
>>root@stack-dev1:~/cms-d# . cms-d/bin/activate
>>(cms-d) root@stack-dev1:~/cms-d# django-admin --version
1.11.5
>>(cms-d) root@stack-dev1:~/cms-d# pip install pillow
Collecting pillow
  Using cached Pillow-4.3.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting olefile (from pillow)
Installing collected packages: olefile, pillow
Successfully installed olefile-0.44 pillow-4.3.0
(cms-d) root@stack-dev1:~/cms-d# pip install djangocms-installer
Collecting djangocms-installer
  Using cached djangocms_installer-0.9.7-py2.py3-none-any.whl
Collecting argparse (from djangocms-installer)
  Using cached argparse-1.4.0-py2.py3-none-any.whl
Collecting six (from djangocms-installer)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting tzlocal (from djangocms-installer)
Requirement already satisfied: pip in ./cms-d/lib/python3.5/site-packages (from djangocms-installer)
Collecting dj-database-url>=0.4 (from djangocms-installer)
  Using cached dj_database_url-0.4.2-py2.py3-none-any.whl
Collecting pytz (from tzlocal->djangocms-installer)
  Using cached pytz-2017.2-py2.py3-none-any.whl
Installing collected packages: argparse, six, pytz, tzlocal, dj-database-url, djangocms-installer
Successfully installed argparse-1.4.0 dj-database-url-0.4.2 djangocms-installer-0.9.7 pytz-2017.2 six-1.11.0 tzlocal-1.4
(cms-d) root@stack-dev1:~/cms-d# mkdir cmsproject
(cms-d) root@stack-dev1:~/cms-d# cd cmsproject
(cms-d) root@stack-dev1:~/cms-d/cmsproject# djangocms -p . cmssite
Creating the project
Please wait while I install dependencies
Dependencies installed
Creating the project
The installation has failed.


*****************************************************************

Check documentation at https://djangocms-installer.readthedocs.io

*****************************************************************

Traceback (most recent call last):
  File "/root/cms-d/cms-d/bin/djangocms", line 11, in <module>
    sys.exit(execute())
  File "/root/cms-d/cms-d/lib/python3.5/site-packages/djangocms_installer/main.py", line 41, in execute
    django.setup_database(config_data)
  File "/root/cms-d/cms-d/lib/python3.5/site-packages/djangocms_installer/django/__init__.py", line 397, in setup_database
    output = subprocess.check_output(command, env=env)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/root/cms-d/cms-d/bin/python3', '-W', 'ignore', 'manage.py', 'migrate']' returned non-zero exit status -9

**Comment by yakky** [comment]
closed due to lack of feedback
