### ISSUE TITLE
django-cms now supports django >=1.10

### ISSUE THREAD

**Issue by superduper** [nephila/djangocms-installer#299]
Hi! 

`django-cms` in 3.4.2 supports recent `django` version: https://github.com/divio/django-cms/commit/dd1b6ee9fca1e1bb23de5475a492270c8a27285d

I wonder what would it take to update `djangocms-installer` to use `django-cms>=3.4.2` along with `django>=1.10`.

UPD: I documented [how I manually updated generated project](https://gist.github.com/superduper/adb941c3b0158c343b14d089c1f60efe) 

Best,
Viktor

**Comment by yakky** [comment]
Version 0.9.4 relased on Jan 3rd already provides support for Django 1.10 with django CMS 3.4

**Comment by superduper** [comment]
@yakky Awesome. Thanks! I didn't see that b/c develop branch shows outdated info and pypi has 0.9.3 package. Will use github version with pip then.

**Comment by yakky** [comment]
@superduper awww snap! I don't know why 0.9.4 wasn't on pypi. I just uploaded it (and synced develop in the process)
Thanks for reporting!

**Comment by superduper** [comment]
@yakky Thank you for releasing `0.9.4`. I tested it with django 1.10 and it failed. See #300 for details.
