### ISSUE TITLE
Hangs on "Please help while I install dependencies"

### ISSUE THREAD

**Issue by GasparPizarro** [nephila/djangocms-installer#315]
Based on [the "community" tutorial](`https://www.django-cms.org/en/,`) I created a virtualenv and installed `djangocms-installer` via `pip`. But when I create a project with the `djangocms` script it hangs while "Please wait while I install dependencies".

```virtualenv -p /usr/bin/python3 --no-site-packages ./python_envs/djangocms_env
pip install djangocms-installer
source ./python_envs/djangocms_env/bin/activate
djangocms mysite
... Creating the project
... Please wait while I install dependencies
```

... And it does not do anything for an hour.

**Comment by yakky** [comment]
@GasparPizarro are you able to install packages via pip?
Apparently pip was stuck trying to download packages
That message is provided only during the ``pip install`` phase
You can try to collect more information by using the ``--verbose`` argument

**Comment by darkhellmgr** [comment]
yeah same here i also got stuck in same phase and waited for an hour but nothing happens. please help

**Comment by yakky** [comment]
which installer version? did you rung with ``--verbose`` argument?

**Comment by GasparPizarro** [comment]
djangocms mysite --verbose
Creating the project
Please wait while I install dependencies
Package install command: install django-cms>=3.5,<3.6 djangocms-admin-style>=1.2,<1.3 django-treebeard>=4.0,<5.0 https://github.com/divio/djangocms-text-ckeditor/archive/master.zip?1521060397.8256114 https://github.com/divio/djangocms-file/archive/master.zip?1521060397.8256114 https://github.com/divio/djangocms-link/archive/master.zip?1521060397.8256114 https://github.com/divio/djangocms-style/archive/master.zip?1521060397.8256114 https://github.com/divio/djangocms-googlemap/archive/master.zip?1521060397.8256114 https://github.com/divio/djangocms-snippet/archive/master.zip?1521060397.8256114 https://github.com/divio/djangocms-picture/archive/master.zip?1521060397.8256114 https://github.com/divio/djangocms-video/archive/master.zip?1521060397.8256114 https://github.com/divio/djangocms-column/archive/master.zip?1521060397.8256114 easy_thumbnails django-filer>=1.3 Django<2.0 pytz django-classy-tags>=0.7 html5lib>=0.999999,<0.99999999 Pillow>=3.0 django-sekizai>=0.9 six

**Comment by yakky** [comment]
Thanks for the update
when it's stuck, the issue is always on the network side.
We don't have any control on the packages installation progress and we can't thus provide any feedback regarding what's going on
I added a slightly different working in 94d1e5e1b756dff2aad0a0db827455da198213e9 but I'm afraid it's the only thing we can do
