### ISSUE TITLE
Use MIDDLEWARE_CLASSES instead of MIDDLEWARE in settings.py generated for django<1.10

### ISSUE THREAD

**Issue by sunmoonone** [nephila/djangocms-installer#316]
Use MIDDLEWARE_CLASSES instead of MIDDLEWARE in settings.py generated for django<1.10

Their will be problems when open cms page while using MIDDLEWARE:
`'WSGIRequest' object has no attribute 'user' `

**Comment by yakky** [comment]
@sunmoonone that should be the case. I just created a project using the defaults (i.e.: Django 1.8) and `MIDDLEWARE_CLASSES' has been added, instead of `MIDDLEWARE`
Can you report the exact version and command you used to generate the project?

**Comment by yakky** [comment]
closed due to lack of feedback
