### ISSUE TITLE
Support Django version >= 2.0 (which supports python >= 3.7)

### ISSUE THREAD

**Issue by schumannd** [nephila/djangocms-installer#331]
is there a reason why Django <2.0 is installed?

I would also add Django 2.0 in the README as not supported, as it is not in beta anymore. (See PR #332)

**Comment by yakky** [comment]
@schumannd no current django CMS version support Django 2.0 and 2.1, thus djangocms-installer can't install newer Django versions as they won't work with django CMS
I will merge #332 plus further clarifications regarding this

**Comment by yakky** [comment]
Hopefully we will be able to bring support for django CMS 3.6rc in the next weeks for Django 2.0 and up support

**Comment by yakky** [comment]
djangocms-installer 1.1rc1 with django cms 3.6 / django 2.0+ will likely be released tomorrow!
