### ISSUE TITLE
Use psycopg2 2.8+ for Django 2.2 and higher

### ISSUE THREAD

**Issue by evgenysizikov** [nephila/djangocms-installer#354]
The introspection issue with psycopg2 2.8 has been fixed in Django 2.2.1 release (see https://code.djangoproject.com/ticket/30331), so that psycopg2 2.8 should be green for Django 2.2 and higher.

djangocms-installer should be updated to use psycopg2 <2.8 for Django >=1.111,<2.2, and the most recent psycopg2 for Django 2.2 and higher.

**Comment by yakky** [comment]
@evgenysizikov thanks for reporting this
re-enabling 2.8 has been on my todolist since the django fix, but I had little bandwidth to handle this
If anyone wants to contribute, it should be quite accessible, otherwise I will try to work on this before the next releease
