### ISSUE TITLE
djangocms 'staticfiles' is not a registered tag library. Must be one of:

### ISSUE THREAD

**Issue by PanosTrak** [nephila/djangocms-installer#366]
I installed djangocms exactly as the docs suggest (but i used pipenv instead of venv) but when i run the server i get an error:
`TemplateSyntaxError at /en/admin/login/
'staticfiles' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_style_tags
admin_tree
admin_tree_list
admin_urls
cache
cms_admin
cms_alias_tags
cms_js_tags
cms_static
cms_tags
djangocms_text_ckeditor_tags
easy_thumbnails_tags
filer_admin_tags
filer_image_tags
filer_tags
i18n
l10n
log
menu_tags
sekizai_tags
snippet_tags
static
thumbnail
tz`

From what i searched this looks like the "{% load staticfiles %}" has be changed to "{% load static %}" in django 3, i went to the source and replaced them where it needed them and then i could login but many things was broken and got the following error:

`The form could not be loaded. Please check that the server is running correctly.`

**Comment by yakky** [comment]
@PanosTrak thanks for reporting this
we are working on a fix

**Comment by yakky** [comment]
Expect djangocms-installer 1.2.3 release in the next hours
Thanks for reporting this issue

**Comment by yakky** [comment]
@PanosTrak djangocms-installer 1.2.3 released with fix

**Comment by yakky** [comment]
Fixed in #368, #367
