### ISSUE TITLE
pip installing from extra-index-url

### ISSUE THREAD

**Issue by philippeowagner** [nephila/djangocms-installer#372]
Hi @yakky et al

Is it possible to pip installing from an extra-index-url?

Thanks in advance for a hint.

**Comment by yakky** [comment]
Hi @philippeowagner you have two main options to add additional sources:

* use `PIP_EXTRA_INDEX_URL` environment variable (https://pip.pypa.io/en/stable/user_guide/#environment-variables)
* provide a custom requirements file via `-r` option (https://djangocms-installer.readthedocs.io/en/latest/reference.html#advanced-options) and declare there `--extra-index-url=...`

**Comment by philippeowagner** [comment]
How could I have missed that... Thanks!
