### ISSUE TITLE
verbose output on demand

### ISSUE THREAD

**Issue by henning** [nephila/djangocms-installer#42]
Up until the point where the installer runs some database stuff, the user can sit a few seconds or longer (e.g. when network is slow and dependencies are installed) in front of the command, appearing nothing is happening.

Even without verbose option chosen, there should be some message to the user that aldryn installer is actually doin something.

It miught also be interesting to only print out all the other stuff - database migrations and such, when verbosity is requested, oitherwise just a short message "running migrations", "installing dependencies" , etc.

**Comment by ojii** [comment]
+1

If a subcommand (eg pip install) fails, there's no way for a user to debug whatever issue there might have been. A flag to not hide all output (and remove -q from pip) would be really helpful.

**Comment by yakky** [comment]
Work in progress in #223

**Comment by yakky** [comment]
Fixed in #223 (there is still room for improvements, but it already proved useful in some cases)
